apiVersion: apps/v1
kind: Deployment
metadata:
  name: typescript-playground
spec:
  replicas: 1
  selector:
    matchLabels:
      app: typescript-playground
  template:
    metadata:
      labels:
        app: typescript-playground
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: api
        image: okteto.dev/typescript-playground:java-maven
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: typescript-playground
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: typescript-playground
spec:
  type: ClusterIP
  ports:
    - name: typescript-playground
      port: 8080
  selector:
    app: typescript-playground
